query($name: String!){
  MediaListCollection(userName: $name, type: ANIME){
    lists{
      name
      isCustomList
      isSplitCompletedList
      entries{
        ... mediaListEntry
      }
    }
  }
  User(name: $name){
    name
    id
    mediaListOptions{
      scoreFormat
    }
  }
}

fragment mediaListEntry on MediaList{
  id
  mediaId
  status
  progress
  repeat
  notes
  priority
  hiddenFromStatusLists
  customLists(asArray: true)
  advancedScores
  startedAt{
    year
    month
    day
  }
  completedAt{
    year
    month
    day
  }
  updatedAt
  createdAt
  media{
    idMal
    title{romaji native english}
    episodes
    format
    countryOfOrigin
    duration
    seasonYear
    season
    duration
  }
  score
  private
}
