query($name: String!){
  MediaListCollection(userName: $name, type: MANGA){
    lists{
      name
      isCustomList
      isSplitCompletedList
      entries{
        ... mediaListEntry
      }
    }
  }
  User(name: $name){
    name
    id
    mediaListOptions{
      scoreFormat
    }
  }
}

fragment mediaListEntry on MediaList{
  mediaId
  status
  progress
  progressVolumes
  repeat
  notes
  priority
  hiddenFromStatusLists
  customLists
  advancedScores
  startedAt{
    year
    month
    day
  }
  completedAt{
    year
    month
    day
  }
  updatedAt
  createdAt
  media{
    idMal
    title{romaji native english}
    volumes
    chapters
    format
    countryOfOrigin
  }
  score
  private
}
